import React, { useState } from "react";
import {
  Modal,
  View,
  Text,
  ScrollView,
  TouchableOpacity,
  StyleSheet,
  Linking,
} from "react-native";
import CenterMessageModal from "./CenterMessageModal";

export default function PolicyModal({ visible, onClose, onAccept }) {
  const handleAccept = () => {
    if (onAccept) onAccept();
    if (onClose) onClose();
  };

  // ✅ CenterMessageModal state
  const [msgOpen, setMsgOpen] = useState(false);
  const [msgType, setMsgType] = useState("info");
  const [msgTitle, setMsgTitle] = useState("");
  const [msgBody, setMsgBody] = useState("");

  const showMsg = (type, title, body = "") => {
    setMsgType(type);
    setMsgTitle(title);
    setMsgBody(body);
    setMsgOpen(true);
  };

  // ✅ open links safely (NO Alert)
  const openLink = async (url) => {
    try {
      if (!url) return;
      const can = await Linking.canOpenURL(url);
      if (!can) return showMsg("error", "Link Error", "Unable to open the link.");
      await Linking.openURL(url);
    } catch {
      showMsg("error", "Link Error", "Unable to open the link.");
    }
  };

  return (
    <>
      <Modal visible={visible} transparent animationType="slide">
        <View style={styles.overlay}>
          <View style={styles.container}>
            {/* Top bar indicator */}
            <View style={styles.dragIndicatorWrapper}>
              <View style={styles.dragIndicator} />
            </View>

            <Text style={styles.title}>Privacy & User Agreements</Text>

            <ScrollView style={styles.scrollArea} showsVerticalScrollIndicator={false}>
              <Text style={styles.policyText}>
                1. We collect your email for account creation and authentication.{"\n\n"}
                2. We store layout images you upload to improve your experience.{"\n\n"}
                3. AI suggestions are generated by third-party models; avoid uploading sensitive information.{"\n\n"}
                4. You may request deletion of your data anytime via Profile → Delete Account.{"\n\n"}
                5. Read the full Privacy Policy and Terms below:
              </Text>

              {/* ✅ clickable links */}
              <TouchableOpacity
                onPress={() => openLink("https://example.com/privacy")}
                activeOpacity={0.85}
              >
                <Text style={styles.linkText}>example.com/privacy</Text>
              </TouchableOpacity>

              <TouchableOpacity
                onPress={() => openLink("https://example.com/terms")}
                activeOpacity={0.85}
              >
                <Text style={styles.linkText}>example.com/terms</Text>
              </TouchableOpacity>
            </ScrollView>

            <View style={styles.buttonRow}>
              <TouchableOpacity onPress={onClose} style={styles.closeButton}>
                <Text style={styles.closeText}>Close</Text>
              </TouchableOpacity>

              <TouchableOpacity onPress={handleAccept} style={styles.agreeButton}>
                <Text style={styles.agreeText}>I Agree</Text>
              </TouchableOpacity>
            </View>
          </View>
        </View>
      </Modal>

      {/* ✅ CenterMessageModal must be outside Modal; wrap in Fragment */}
      <CenterMessageModal
        visible={msgOpen}
        type={msgType}
        title={msgTitle}
        message={msgBody}
        onClose={() => setMsgOpen(false)}
      />
    </>
  );
}

const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.4)",
    justifyContent: "flex-end",
  },
  container: {
    maxHeight: "80%",
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
  },
  dragIndicatorWrapper: {
    alignItems: "center",
    marginBottom: 12,
  },
  dragIndicator: {
    width: 48,
    height: 4,
    backgroundColor: "#DDD",
    borderRadius: 2,
  },
  title: {
    fontSize: 20,
    fontWeight: "700",
    marginBottom: 12,
    color: "#111827",
  },
  scrollArea: {
    marginBottom: 20,
  },
  policyText: {
    fontSize: 15,
    lineHeight: 22,
    color: "#374151",
  },
  linkText: {
    fontSize: 15,
    lineHeight: 22,
    color: "#01579B",
    fontWeight: "700",
    marginTop: 6,
  },
  buttonRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
  },
  closeButton: {
    flex: 1,
    padding: 12,
    borderWidth: 1,
    borderColor: "#DDD",
    borderRadius: 12,
    alignItems: "center",
  },
  closeText: {
    fontWeight: "600",
    color: "#111827",
  },
  agreeButton: {
    flex: 1,
    padding: 12,
    backgroundColor: "#0F3E48",
    borderRadius: 12,
    alignItems: "center",
  },
  agreeText: {
    color: "#FFFFFF",
    fontWeight: "700",
  },
});
